name: Java CI and Push Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build project with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Verify Build Artifacts
        run: |
          echo "Checking target directory contents..."
          ls -R target || { echo "No build artifacts found!"; exit 1; }

      - name: Prepare artifacts for push
        run: |
          echo "Preparing artifacts for upload..."
          mkdir -p artifacts
          cp target/*.jar artifacts/ || echo "No JAR files found."
          cp -r target/site/apidocs artifacts/ || echo "No APIDOCS found."
          ls -R artifacts

      - name: Push artifacts to 'artifacts' branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          # Fetch and prepare artifacts branch
          git fetch origin
          git checkout artifacts || git checkout -b artifacts

          # Copy artifacts
          mkdir -p build-artifacts
          cp -r artifacts/* build-artifacts/
          git add build-artifacts/

          # Commit and push changes
          git commit -m "Add build artifacts (JAR and APIDOCS) from CI build" || echo "No changes to commit."
          git push origin artifacts
