name: Create Release Tag

on:
  push:
    paths:
      - "pom.xml"
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Read version from pom.xml
        id: read_version
        run: |
          VERSION=$(xmllint --xpath "string(//*[local-name() = 'project']/*[local-name() = 'version'])" pom.xml)
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Create and push tag
        env:
          VERSION: ${{ env.version }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag "v$VERSION"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} "v$VERSION"